/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.spc.deep;import cn.zhuatech.spc.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                         */
@RestController @RequestMapping("/api/spc-ops") public class DeepDomainController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                             */
public DeepDomainController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                        */
@GetMapping("/dashboard")ApiResponse<?> dashboard(@RequestParam String organizationCode){return ApiResponse.ok(s.dashboard(organizationCode));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/characteristics")ApiResponse<?> create(@Valid @RequestBody DeepDomainService.CharacteristicRequest r){return ApiResponse.ok(s.create(r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/characteristics/{id}/samples")ApiResponse<?> sample(@PathVariable Long id,@Valid @RequestBody DeepDomainService.SampleRequest r){return ApiResponse.ok(s.sample(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
@PostMapping("/signals/{id}/assign")ApiResponse<?> assign(@PathVariable Long id,@Valid @RequestBody DeepDomainService.AssignRequest r){return ApiResponse.ok(s.assign(id,r));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
@PostMapping("/signals/{id}/corrective-action")ApiResponse<?> corrective(@PathVariable Long id,@Valid @RequestBody DeepDomainService.CorrectiveRequest r){return ApiResponse.ok(s.corrective(id,r));}}
