/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.spc.deep;import cn.zhuatech.spc.common.ApiResponse;import jakarta.validation.Valid;import org.springframework.web.bind.annotation.*;/**
                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                         */
@RestController @RequestMapping("/api/admin/spc-ops") public class DeepAdminController{private final DeepDomainService s;/**
                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                  */
public DeepAdminController(DeepDomainService s){this.s=s;}/**
                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                            */
@PostMapping("/characteristics/{id}/activate")ApiResponse<?> activate(@PathVariable Long id){return ApiResponse.ok(s.activate(id));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/signals/{id}/verify")ApiResponse<?> verify(@PathVariable Long id,@Valid @RequestBody DeepDomainService.VerifyRequest r){return ApiResponse.ok(s.verify(id,r));}}
