/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.spc.deep;import cn.zhuatech.spc.model.AuditLog;import cn.zhuatech.spc.repository.AuditLogRepository;import jakarta.persistence.*;import jakarta.validation.constraints.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Service @Transactional(readOnly=true) public class DeepDomainService{private final EntityManager em;private final AuditLogRepository logs;/**
                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                            */
public DeepDomainService(EntityManager e,AuditLogRepository l){em=e;logs=l;}/**
                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                        */
public Dashboard dashboard(String o){return new Dashboard(characteristics(o),signals(o));}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public CharacteristicView create(CharacteristicRequest r){if(!(r.lowerSpecLimit()<r.targetValue()&&r.targetValue()<r.upperSpecLimit()))throw bad("目标值必须位于规格上下限之间");var c=new ProcessCharacteristic(r.organizationCode(),r.characteristicCode(),r.name(),r.unit(),r.targetValue(),r.lowerSpecLimit(),r.upperSpecLimit(),r.sigma());em.persist(c);audit("SPC_CHARACTERISTIC","创建质量特性",c.characteristicCode,c.name);return view(c);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
@Transactional public CharacteristicView activate(Long id){var c=characteristic(id);if(!"DRAFT".equals(c.status))throw conflict("只有草稿特性可以启用");if(c.sigma<=0)throw conflict("启用前必须配置有效过程标准差");c.status="ACTIVE";audit("SPC_CHARACTERISTIC","启用控制图",c.characteristicCode,"sigma="+c.sigma);return view(c);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public SampleResult sample(Long id,SampleRequest r){var c=characteristic(id);if(!"ACTIVE".equals(c.status))throw conflict("质量特性未启用");double ucl=c.targetValue+3*c.sigma,lcl=c.targetValue-3*c.sigma;String rule=null;if(r.measuredValue()>ucl||r.measuredValue()<lcl)rule="RULE_1_BEYOND_3_SIGMA";if(rule==null){var previous=em.createQuery("select s from ProcessSample s where s.characteristicId=:id order by s.sampledAt desc",ProcessSample.class).setParameter("id",id).setMaxResults(7).getResultList();if(previous.size()==7){boolean above=r.measuredValue()>c.targetValue&&previous.stream().allMatch(x->x.measuredValue>c.targetValue),below=r.measuredValue()<c.targetValue&&previous.stream().allMatch(x->x.measuredValue<c.targetValue);if(above||below)rule="RULE_2_EIGHT_ON_ONE_SIDE";}}var s=new ProcessSample(id,r.sampleNo(),r.measuredValue(),r.subgroup(),r.sampledAt(),rule!=null);em.persist(s);Long signalId=null;if(rule!=null){var x=new ProcessSignal(id,s.id,"SIG-"+r.sampleNo(),rule,"测量值 "+r.measuredValue()+" 触发 "+rule,"HIGH");em.persist(x);signalId=x.id;}audit("SPC_SAMPLE","采集样本",r.sampleNo(),rule==null?"IN_CONTROL":rule);return new SampleResult(view(s),rule,signalId,lcl,ucl);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 @Transactional public SignalView assign(Long id,AssignRequest r){var s=signal(id);if(!"OPEN".equals(s.status))throw conflict("只有待处理信号可以分派");s.owner=r.owner();s.status="INVESTIGATING";audit("SPC_CAPA","分派异常",s.signalNo,r.owner());return view(s);}/**
                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                       */
@Transactional public SignalView corrective(Long id,CorrectiveRequest r){var s=signal(id);if(!"INVESTIGATING".equals(s.status))throw conflict("异常必须先分派调查");if(!r.evidenceHash().matches("[a-fA-F0-9]{64}"))throw bad("证据摘要必须为64位SHA-256");s.rootCause=r.rootCause();s.correctiveAction=r.correctiveAction();s.evidenceHash=r.evidenceHash().toLowerCase();s.status="READY_VERIFY";audit("SPC_CAPA","提交纠正措施",s.signalNo,r.rootCause());return view(s);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */
@Transactional public SignalView verify(Long id,VerifyRequest r){var s=signal(id);if(!"READY_VERIFY".equals(s.status))throw conflict("只有待验证措施可以复核");s.verificationNote=r.note();s.status=r.effective()?"CLOSED":"INVESTIGATING";audit("SPC_CAPA",r.effective()?"措施验证通过":"措施验证退回",s.signalNo,r.note());return view(s);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private List<CharacteristicView>characteristics(String o){return em.createQuery("select c from ProcessCharacteristic c where c.organizationCode=:o order by c.createdAt desc",ProcessCharacteristic.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                    */
private List<SignalView>signals(String o){return em.createQuery("select s from ProcessSignal s where s.characteristicId in(select c.id from ProcessCharacteristic c where c.organizationCode=:o) order by s.createdAt desc",ProcessSignal.class).setParameter("o",o).getResultList().stream().map(this::view).toList();}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            */
private ProcessCharacteristic characteristic(Long id){var x=em.find(ProcessCharacteristic.class,id);if(x==null)throw missing("质量特性不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              */
private ProcessSignal signal(Long id){var x=em.find(ProcessSignal.class,id);if(x==null)throw missing("过程异常不存在");return x;}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
private void audit(String m,String a,String n,String d){logs.save(new AuditLog(m,a,n,"spc-domain",d));}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */
private ResponseStatusException conflict(String m){return new ResponseStatusException(HttpStatus.CONFLICT,m);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
private ResponseStatusException missing(String m){return new ResponseStatusException(HttpStatus.NOT_FOUND,m);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 private CharacteristicView view(ProcessCharacteristic c){double cp=(c.upperSpecLimit-c.lowerSpecLimit)/(6*c.sigma),cpk=Math.min(c.upperSpecLimit-c.targetValue,c.targetValue-c.lowerSpecLimit)/(3*c.sigma);return new CharacteristicView(c.id,c.organizationCode,c.characteristicCode,c.name,c.unitName,c.targetValue,c.lowerSpecLimit,c.upperSpecLimit,c.sigma,c.status,Math.round(cp*100d)/100d,Math.round(cpk*100d)/100d,c.version);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                          */
private SampleView view(ProcessSample s){return new SampleView(s.id,s.characteristicId,s.sampleNo,s.measuredValue,s.subgroup,s.sampledAt,s.outOfControl);}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
private SignalView view(ProcessSignal s){return new SignalView(s.id,s.characteristicId,s.sampleId,s.signalNo,s.ruleCode,s.description,s.severity,s.status,s.owner,s.rootCause,s.correctiveAction,s.evidenceHash,s.verificationNote,s.version);}
 /**
  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
  */
 public record CharacteristicRequest(@NotBlank String organizationCode,@NotBlank String characteristicCode,@NotBlank String name,@NotBlank String unit,double targetValue,double lowerSpecLimit,double upperSpecLimit,@Positive double sigma){}/**
                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                */
public record SampleRequest(@NotBlank String sampleNo,double measuredValue,@NotBlank String subgroup,@NotNull LocalDateTime sampledAt){}/**
                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                        */
public record AssignRequest(@NotBlank String owner){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                             * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                             */
public record CorrectiveRequest(@NotBlank String rootCause,@NotBlank String correctiveAction,@NotBlank String evidenceHash){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */
public record VerifyRequest(boolean effective,@NotBlank String note){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public record CharacteristicView(Long id,String organizationCode,String characteristicCode,String name,String unit,double target,double lsl,double usl,double sigma,String status,double cp,double cpk,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
public record SampleView(Long id,Long characteristicId,String sampleNo,double measuredValue,String subgroup,LocalDateTime sampledAt,boolean outOfControl){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */
public record SignalView(Long id,Long characteristicId,Long sampleId,String signalNo,String ruleCode,String description,String severity,String status,String owner,String rootCause,String correctiveAction,String evidenceHash,String verificationNote,long version){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        */
public record SampleResult(SampleView sample,String triggeredRule,Long signalId,double lcl,double ucl){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public record Dashboard(List<CharacteristicView>characteristics,List<SignalView>signals){}
}
