/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.spc.deep;import jakarta.persistence.*;import java.time.*;
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="spc_characteristics",uniqueConstraints=@UniqueConstraint(columnNames={"organizationCode","characteristicCode"})) class ProcessCharacteristic{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false,length=40)String organizationCode;@Column(nullable=false,length=50)String characteristicCode;@Column(nullable=false,length=120)String name;@Column(nullable=false,length=30)String unitName;double targetValue;double lowerSpecLimit;double upperSpecLimit;double sigma;@Column(nullable=false,length=20)String status="DRAFT";LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
protected ProcessCharacteristic(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
ProcessCharacteristic(String o,String c,String n,String u,double t,double l,double h,double s){organizationCode=o;characteristicCode=c;name=n;unitName=u;targetValue=t;lowerSpecLimit=l;upperSpecLimit=h;sigma=s;createdAt=LocalDateTime.now();}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="spc_samples",uniqueConstraints=@UniqueConstraint(columnNames={"characteristicId","sampleNo"})) class ProcessSample{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Column(nullable=false)Long characteristicId;@Column(nullable=false,length=60)String sampleNo;double measuredValue;@Column(nullable=false,length=50)String subgroup;LocalDateTime sampledAt;boolean outOfControl;/**
                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                       */
protected ProcessSample(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
ProcessSample(Long c,String n,double v,String g,LocalDateTime at,boolean o){characteristicId=c;sampleNo=n;measuredValue=v;subgroup=g;sampledAt=at;outOfControl=o;}}
/**
 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
 */
@Entity @Table(name="spc_signals",uniqueConstraints=@UniqueConstraint(columnNames="signalNo")) class ProcessSignal{@Id @GeneratedValue(strategy=GenerationType.IDENTITY)Long id;@Version long version;@Column(nullable=false)Long characteristicId;Long sampleId;@Column(nullable=false,length=50)String signalNo;@Column(nullable=false,length=40)String ruleCode;@Column(nullable=false,length=300)String description;@Column(nullable=false,length=20)String severity;@Column(nullable=false,length=25)String status="OPEN";@Column(length=50)String owner;@Column(length=400)String rootCause;@Column(length=400)String correctiveAction;@Column(length=64)String evidenceHash;@Column(length=400)String verificationNote;LocalDateTime createdAt;/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       */
protected ProcessSignal(){}/**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  */
ProcessSignal(Long c,Long s,String n,String r,String d,String severity){characteristicId=c;sampleId=s;signalNo=n;ruleCode=r;description=d;this.severity=severity;createdAt=LocalDateTime.now();}}
